### ISSUE TITLE
Errors when using this plugin without powerpress

### ISSUE THREAD

**Issue by saerdnaer** [Lehmancreations/Podcast-Namespace-Wordpress-Plugin#4]
I do not know if this is actually the scope of this plugin, but the feed generator part does not work when powerpress is not installed:

```
2021-02-13 08:45:03: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function powerpress_is_podcast_feed() in /srv/www/wordpress/wp-content/plugins/Podcast-Namespace-Wordpress-Plugin/podcastindex.php:258
2021-02-13 08:45:03: (mod_fastcgi.c.421) FastCGI-stderr: Stack trace:
2021-02-13 08:45:03: (mod_fastcgi.c.421) FastCGI-stderr: #0 /srv/www/wordpress/wp-includes/class-wp-hook.php(287): podcastindex_rss2_ns('')
2021-02-13 08:45:03: (mod_fastcgi.c.421) FastCGI-stderr: #1 /srv/www/wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
2021-02-13 08:45:03: (mod_fastcgi.c.421) FastCGI-stderr: #2 /srv/www/wordpress/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
2021-02-13 08:45:03: (mod_fastcgi.c.421) FastCGI-stderr: #3 /srv/www/wordpress/wp-includes/feed-rss2.php(36): do_action('rss2_ns')
2021-02-13 08:45:03: (mod_fastcgi.c.421) FastCGI-stderr: #4 /srv/www/wordpress/wp-includes/template.php(730): require_once('/srv/www/wordpr...')
2021-02-13 08:45:03: (mod_fastcgi.c.421) FastCGI-stderr: #5 /srv/www/wordpress/wp-includes/functions.php(1617): load_template('/srv/www/wordpr...')
2021-02-13 08:45:03: (mod_fastcgi.c.421) FastCGI-stderr: #6 /srv/www/wordpress/wp-includes/class-wp-hook.php(289): do_feed_rss2(false)
2021-02-13 08:45:03: (mod_fastcgi.c.421) FastCGI-stderr: #7 /srv/www/wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
2021-02-13 08:45:03: (mod_fastcgi.c.421) FastCGI-stderr: #8 /srv/www/wordpress/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
2021-02-13 08:45:03: (mod_fastcgi.c.421) FastCGI-stderr: #9 /srv/www/wordpress/wp-includes/functions.php(1579): do_action('do_feed_rss2', false, 'r in /srv/www/wordpress/wp-content/plugins/Podcast-Namespace-Wordpress-Plugin/podcastindex.php on line
```

**Comment by Lehmancreations** [comment]
It really isn't within the scope. I built the plugin in such a way that it uses a filter from power press to see if it is a powerpress feed because I did not want to add the tags to other non podcast feeds on my site.
